name: Daily Newspaper Bot

on:
  schedule:
    - cron: '0 4 * * *' # 00:00 UTC = 06:30 AM MM Time
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Bot Script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python bot_auto.py
        
      - name: Keepalive Commit
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git pull --rebase
          git commit --allow-empty -m "keepalive" || echo "No changes to commit"
          git push
